// Code generated by MockGen. DO NOT EDIT.
// Source: greeting.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGreetingUseCaseInterface is a mock of GreetingUseCaseInterface interface.
type MockGreetingUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGreetingUseCaseInterfaceMockRecorder
}

// MockGreetingUseCaseInterfaceMockRecorder is the mock recorder for MockGreetingUseCaseInterface.
type MockGreetingUseCaseInterfaceMockRecorder struct {
	mock *MockGreetingUseCaseInterface
}

// NewMockGreetingUseCaseInterface creates a new mock instance.
func NewMockGreetingUseCaseInterface(ctrl *gomock.Controller) *MockGreetingUseCaseInterface {
	mock := &MockGreetingUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockGreetingUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGreetingUseCaseInterface) EXPECT() *MockGreetingUseCaseInterfaceMockRecorder {
	return m.recorder
}

// Greet mocks base method.
func (m *MockGreetingUseCaseInterface) Greet(name string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Greet", name)
	ret0, _ := ret[0].(string)
	return ret0
}

// Greet indicates an expected call of Greet.
func (mr *MockGreetingUseCaseInterfaceMockRecorder) Greet(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Greet", reflect.TypeOf((*MockGreetingUseCaseInterface)(nil).Greet), name)
}
